title: Ultimate Consequences
description: A comprehensive database of deaths in Bolivian political conflict
theme: just-the-docs

url: https://ultimateconsequences.github.io

aux_links:
  Carwil Bjork-James at Vanderbilt: https://my.vanderbilt.edu/cbjorkjames/
  Blog: https://woborders.blog  
