project: 
  type: website
  output-dir: docs
  resources: 
    - images/*
    - Geocoding.html
    - project-documentation/*
    - domains/*
    - municipalities/*

execute:
  freeze: auto  # re-render only when source changes

website: 
  page-navigation: true
  title: "Ultimate Consequences" 
  site-url: "https://ultimateconsequences.github.io/" 
  favicon: favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "Ultimate Consequences research website"
    
  sidebar:
    logo: "images/Bolivia-UC-icon-312px.png"
    logo-alt: "Ultimate Consequences"
    title: "Lethal Political Conflict in Bolivia"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://ultimateconsequences.github.io
        text: "Ultimate Consequences Project Website"
      - icon: wordpress
        href: https://woborders.blog/posts/bolivia/
        text: "Bolivia on Carwil without Borders blog"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - section: ultimate-consequences/About.md
        contents:
          - ultimate-consequences/Methodology.md
          - ultimate-consequences/Codebook-current.md
      - section: ultimate-consequences/Visualizations.md
        contents:
          - href: vis/Nested-Table.Rmd
            text: "Directory of event & individuals"
          - href: vis/Directorio-Eventos-Muertes.Rmd
            text: "Directorio cronológico de muertes"
          - href: vis/Choropleth-Map-Municipality.html
            text: "Map by Municipality"
          - href: vis/Choropleth-Map-Municipality-es.html
            text: "Mapa por Municipio"
          - dashboards.qmd
      - section: "Data Pages for Publications"
        contents:
          - href: ultimate-consequences/BSJ-Political-Violence.Rmd
            text: "Tactics of Political Violence in 2019"
          - href: ultimate-consequences/WLRF-Tables.Rmd
            text: "When Does Lethal Repression Fail?"
      - text: "---"
      - section: "Research Team"
        contents:
          - team/carwil-bjork-james.qmd
      - text: "---"

format:
  html:
    theme: 
      light: yeti
      dark: slate
    mainfont: "Open Sans"
    code-copy: true
    code-overflow: wrap
    toc: true

filters:
  - include-files.lua


  
