---
title: "Directorio cronológico de muertes en conflictos políticos bolivianos, octubre 1982 - mayo 2023 "
output:
  html_document:
    df_print: tibble
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(datawizard) # putting first because of conflicts/masking
library(googlesheets4)
library(googledrive)
library(tidyr)
library(readr)
library(dplyr)
library(stringr)
library(reactable)
library(RColorBrewer)
library(forcats)

```

```{r import-settings, echo=FALSE, include=FALSE}
# Use "src/00-import-settings-live.R" to live-import from Google Sheets
# Use "src/00-import-settings-local.R" to load the most-updated local file
#
# These can be put in the chunk heading as file="src/00-import-settings-local.R",
# or in the body of the chunk as source("filename", local = knitr::knit_global()),
# but source() seems to behave better
library(here)

source(here::here("src","00-import-settings-local.R"), local = knitr::knit_global())
```

```{r import, echo=FALSE, include=FALSE}
source(here::here("src","01-import.R"), local = knitr::knit_global())

de.imported <- de

# filter the entries for:
# unconfirmed deaths
# collateral deaths
# nonconflict accident deaths
def <- de %>%
  filter(is.na(unconfirmed) | unconfirmed != TRUE) %>%
  filter(is.na(intentionality) | intentionality != "Collateral") %>%
  filter(is.na(intentionality) | !str_detect(intentionality, "Nonconflict"))

de.confirmed <- def

# de <- def # AUTOFILTERING. Comment out when we want to consider the whole dataset
          # Also, eventually we may want to handle "unconfirmed" in a more complex way
          #   At that point, we will no longer filter for it, but pass it through.

# Narrow filter leaves in unconfirmed events to be labeled below.
de <- de %>% 
  filter(is.na(intentionality) | intentionality != "Collateral") %>%
  filter(is.na(intentionality) | !str_detect(intentionality, "Nonconflict"))
```

```{r enable-translation, echo=FALSE, include=FALSE}
live.import <- FALSE # load variable translation table locally 
source(here::here("src", "01-import-variable-table.R"))
# Imports the horizontal lookup table var_name_table
# and creates the function variable_name
#                 function(variable, lang="en", name_table = var_name_table)
# varable_name takes an input of the variable name and outputs the name in the specificied language

source(here::here("src", "02-load-translation-tables.R"))
# translation: A compound list of all the translation tables,
#              labeled by the corresponding variable
# Here's its structure…
# translation <- list(protest_domain = domain_trans_table,
#                     pres_admin = pres_trans_table,
#                     dec_affiliation = affil_trans_table,
#                     perp_affiliation = affil_trans_table, # This duplicate makes referencing easier
#                     cause_death = cause_trans_table,
#                     state_responsibility = sresp_trans_table, 
#                     intentionality = intent_trans_table,
#                     event_title = event_trans_table
# )

lang_chosen <- "es" # This is a single language RMarkdown file
                    # A further refinement would either:
                    # 1. allow the language to be selected via a RMarkdown parameter
                    # 2. build multiple language panes into the same html document

var_lang <- function(...){
  variable_name(..., lang = lang_chosen, name_table = var_name_table)
}
```

```{r factor_presadmin, include=FALSE}
library(janitor) # for tabyl
source(here::here("src","data-cleaning.R"), local = knitr::knit_global())

president_levels <- c(
  "Hernán Siles Zuazo", "Víctor Paz Estenssoro", "Jaime Paz Zamora", 
  "Gonzalo Sanchez de Lozada (1st)", "Hugo Banzer (2nd)", "Jorge Quiroga",
  "Gonzalo Sanchez de Lozada (2nd)", "Carlos Diego Mesa Gisbert", 
  "Eduardo Rodríguez", "Evo Morales", "Interim military government", 
  "Jeanine Áñez", "Luis Arce")
de <- de %>% mutate(pres_admin=factor(pres_admin, levels=president_levels))

state_resp.colors <-  c(
  Perpetrator = "forestgreen", 
  Victim = "#cd6600",                  # "darkorange3",
  Involved = "#90ee90",                # "lightgreen",         
  Separate = "#eeb422",                # "goldenrod2",
  Unintentional = "darkgray",
  Unknown = "lightgray")

state_resp.colors_es <-  c(
  Perpetrador = "forestgreen", 
  Víctima = "#cd6600",                  # "darkorange3",
  Involucrado = "#90ee90",                # "lightgreen",         
  Separado = "#eeb422",                # "goldenrod2",
  "No Intencional" = "darkgray",
  Desconocido = "lightgray")

de <- de %>% mutate(state_responsibility = case_when(    # overwrite the state responsibility for unintentional cases
                                   intentionality == "Incidental" ~ "Incidental",
                                   intentionality == "Conflict Accident" ~ "Accidental",
                                   TRUE ~ state_responsibility))

de$state_responsibility <- convert_na_to(de$state_responsibility, replacement = "Unknown")
de$state_responsibility <- fct_collapse(de$state_responsibility, 
                             Perpetrator = c("State perpetrator", "State likely perpetrator", 
                                             "State perpetrator, State victim refusing orders", 
                                             "State perpetrator, State victim in mutiny",
                                             "State indirect perpetrator"),
                             Involved = c("State involved", "Political victim", 
                                          "Political victim / political perpetrator",
                                          "Political victim / unknown perpetrator",
                                          "Possibly state involved"),
                             Victim = c("State victim",  
                                        "State victim, State perpetrator in mutiny"), 
                             Separate = c("Separate from state"),
                             Unintentional = c("Incidental", "Accidental"),
                             Unknown  = c("Unknown", "Unclear") )

sr_levels <- c("Perpetrator", "Victim", "Involved", "Separate", "Unintentional", "Unknown")
de$state_responsibility <- fct_relevel(de$state_responsibility, sr_levels)

de <- de %>% mutate(age = round(dec_age, digits = 0))
```

```{r calculate-event-table, echo=FALSE, message=FALSE, warning=FALSE}
# create an event count by title that also counts the number of state perpetrator 
#   and state victim deaths
#
# This table is generated using the variable: de
source(here::here("src","event-responsibility-dated.R"), local = knitr::knit_global())
```

```{r event_table, include=FALSE, message=FALSE, results='asis'}
library(reactable)
library(reactablefmtr)

## Color scales
red_pal <- function(x) rgb(colorRamp(c("#ffe0e0", "#ff3030", "#bb2020"))(x), maxColorValue = 255)
perp_pal <- function(x) rgb(colorRamp(c("#eeeeee", state_resp.colors[["Perpetrator"]]))(x), maxColorValue = 255)
sv_pal <- function(x) rgb(colorRamp(c("#eeeeee", state_resp.colors[["Victim"]]))(x), maxColorValue = 255)
sep_pal  <- function(x) rgb(colorRamp(c("#eeeeee", state_resp.colors[["Separate"]]))(x), maxColorValue = 255)

# alternate calculation of span
max_deaths <- max(select(event.responsibility, n:n_state_victim),  na.rm=TRUE)
max_sv_deaths <- max(select(event.responsibility, n_state_victim), na.rm=TRUE)
max_sep_deaths <- max(select(event.responsibility, n_state_separate), na.rm=TRUE)
# max_deaths <- max(max_deaths, max_larger) # allows a function call to include a top value

# deaths columns formatting
deaths_column <- function(maxWidth = 60, class = NULL, maxValue = 100, chosen_palette = red_pal, ...) {
  colDef(
    maxWidth = maxWidth,
    defaultSortOrder = "desc",
    style = function(value) {
      # Lighter color for <1%
      if (value / maxValue < 0.01) {
        list(color = "#888", background="#fff")
      } else {
        list(color = case_when(sqrt(value/ maxValue) < .48 ~ "#111",
                               TRUE ~ "#eee"), 
             background = chosen_palette((value/ maxValue)^0.8),
             fontWeight = "bold")
      }
    },
    ...
  )
}

tbl <- reactable(event.responsibility,
                 filterable=TRUE,
                 theme = nytimes(),
                 defaultPageSize=25,
                 pageSizeOptions = c(10, 25, 40, 60, 100),
                 showPageSizeOptions=TRUE,
                 defaultColDef = colDef(
                   filterable=FALSE,
                   defaultSortOrder = "desc",
                   minWidth = 30, maxWidth=50),
                 columnGroups = list(colGroup(name = "deaths", columns =
                                                er.numerical.columns)
                 ),
                 columns = list (
                   event_title = colDef (name="Event", maxWidth=250,
                                         defaultSortOrder = "asc",
                                         filterable=TRUE,
                                         style = list(fontWeight = "bold")),
                   date = colDef(name="Year", maxWidth=60,
                                 cell = function(value) strftime(value, "%Y"),
                                 defaultSortOrder = "asc",
                                 filterable=TRUE, sortNALast = TRUE,
                                 style = list(background = "#ffffff")),
                   year = colDef (show = FALSE),
                   # year = colDef (name="Year", maxWidth=60,
                   #                defaultSortOrder = "asc",
                   #                filterable=TRUE, sortNALast = TRUE,
                   #                style = list(background = "#ffffff")),
                   n = deaths_column(maxValue = max_deaths, name="Confirmed"),
                   n_state_perp = deaths_column(maxValue = max_deaths, name="State Perp",
                                                chosen_palette = perp_pal),
                   n_state_victim = deaths_column(maxValue = max(max_deaths/2, max_sv_deaths),
                                                  # sets the maximum intensity
                                                  name="State Victim",
                                                  chosen_palette = sv_pal),
                   n_state_separate = deaths_column(maxValue = max(max_deaths/2, max_sep_deaths),
                                                    # sets the maximum intensity
                                                    name="Sep from State",
                                                    chosen_palette = sep_pal),
                   protest_domain = colDef (name="Protest Domain",
                                            defaultSortOrder = "asc",
                                            filterable=TRUE,
                                            maxWidth=150),
                   pres_admin = colDef (name="President",
                                        defaultSortOrder = "asc",
                                        filterable=TRUE, maxWidth=300)
                 )
)

tbl
cat("Categories of deaths may not add to the total because conflict accidents are excluded. \n\n")
cat(paste(datafiles_footer(),sep=""))
```

### Tabla de datos, organizado por evento

Esta tabla se puede ordenar por cualquiera de sus variables y buscar por las variables de texto así como por el año. En la parte inferior, puede elegir cuántos eventos mostrar o recorrer los eventos.

Usando los triángulos a la izquierda, puede acceder a las muertes individuales.

```{r drill-down-table, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
library(lubridate)
library(reactable)
library(reactablefmtr)

top_level <- event.responsibility %>% arrange(date)

top_level_es <- top_level %>% 
  left_join(translation$protest_domain, by = c("protest_domain"="en")) %>%
  rename(protest_domain_es = es) %>%
  left_join(translation$pres_admin, by = c("pres_admin"="en")) %>%
  rename(pres_admin_es = es) %>% 
  left_join(translation$event_title, by = c("event_title"="en")) %>%
  rename(event_title_es = es) %>%
  rename(event_title_en = event_title) %>%
  select(-protest_domain, -pres_admin) %>%
  rename(pres_admin = pres_admin_es) %>%
  rename(protest_domain = protest_domain_es) %>%
  rename(event_title = event_title_es) %>%
  relocate(event_title) %>%
  relocate(event_title_en, .after = last_col()) # keeping this column to match

# de <- de %>% mutate(intentionality = case_when(
#                                     unconfirmed == TRUE ~ str_c(intentionality, " (unconfirmed)"),
#                                     TRUE ~ intentionality))

second_level <- de %>% 
                   combine_dates(incl_laterdate=FALSE) %>%
                   select(event_title, date, dec_firstname, dec_surnames, age,
                                         dec_affiliation, 
#  no translation available yet for….      cause_death, 
# When it is, remove the commented lines in the next statement (and test)
                                         perp_affiliation,
                                         state_responsibility, intentionality, unconfirmed)

second_level_es <- second_level %>% 
  left_join(translation$dec_affiliation, by = c("dec_affiliation"="en")) %>%
  rename(dec_affiliation_es = es) %>%
  left_join(translation$perp_affiliation, by = c("perp_affiliation"="en")) %>%
  rename(perp_affiliation_es = es) %>%
  left_join(translation$state_responsibility, by = c("state_responsibility"="en")) %>%
  rename(state_responsibility_es = es) %>%
  left_join(translation$intentionality, by = c("intentionality"="en")) %>%
  rename(intentionality_es = es) %>%
#  left_join(translation$cause_death, by = c("intentionality"="en")) %>%
#  rename(cause_death_es = es) %>%
  select(event_title, date, dec_firstname, dec_surnames, age, dec_affiliation_es,
#           cause_death_es,
            perp_affiliation_es, state_responsibility_es, intentionality_es, unconfirmed) %>%
  rename(dec_affiliation = dec_affiliation_es) %>%
  rename(perp_affiliation = perp_affiliation_es) %>%
  rename(state_responsibility = state_responsibility_es) %>%
#  rename(cause_death = cause_death_es) %>%
  rename(intentionality = intentionality_es) 
                                    
                                    
second_level_es <- second_level_es %>% mutate(intentionality = case_when(
                                     unconfirmed == TRUE ~ str_c(intentionality, " (no confirmado)"),
                                     TRUE ~ intentionality)) %>% 
                                     select(-unconfirmed)
            

# reactable(second_level_es)

# Translation Switching Code
# =========================
# Translation table entries for 
n_trans_table <- tribble(
  ~date, ~age, ~n, ~n_state_perp, ~n_state_victim, ~n_state_separate, ~language, ~deaths,
  #--|--|----
  "Date", "Age", "Confirmed", "State Perp", "State Victim", "Sep from State", "en", "Deaths",
  "Fecha", "Edad", "Confirmado", "Perp x Estado", "Víctima Estatal", "Ajeno del Estado", "es", "Muertes",
  "date", "age", "n", "n_state_perp", "n_state_victim", "n_state_separate", "r_variable", "deaths"
)

if (identical(n_trans_table$language, var_name_table$language)){
   var_name_table2 <- bind_cols(var_name_table, select(n_trans_table, -language))
}else{
  warning("Translation table for this interactive table does not match the format of the overall translation table and will not be deployed.")
}

var_lang <- function(...){
  variable_name(..., lang = lang_chosen, name_table = var_name_table2)
}

prev <- Sys.getlocale("LC_TIME")

date_locale <- "en-US"
# date_locale <- Sys.getenv("LANG") # Should work but has a slightly different format 

# Future addition:
# To make reactable interface elements switchable,
# Save the reactableLang English settings here

if (lang_chosen=="es"){
  top_level <- top_level_es
  second_level <- second_level_es
  date_locale <- "es-BO"
  sink(nullfile()) # suppress output
  Sys.setlocale("LC_TIME", "es_ES.UTF-8")
  sink()           # end suppress output
  # … and insert the reactableLang() settings here
}

# Spanish language text for reactable interface
# =============================================
reactable_es_1 <- reactableLang(
    searchPlaceholder = "Busqueda",
    noData = "Sin coincidencias",
    pageInfo = "{rowStart} a {rowEnd} de {rows} eventos", # <-only difference is here
    pagePrevious = "\u276e",
    pageNext = "\u276f",
    pageSizeOptions = "Mostrar {rows}",        
    # Accessible labels for assistive technologies such as screen readers.
    # These are already set by default, but don't forget to update them when
    # changing visible text.
    pagePreviousLabel = "Página anterior",
    pageNextLabel = "Siguiente página"
  )

reactable_es_2 <- reactableLang(
    searchPlaceholder = "Busqueda",
    noData = "Sin coincidencias",
    pageInfo = "{rowStart} a {rowEnd} de {rows} muertes", # <-only difference is here
    pagePrevious = "\u276e",
    pageNext = "\u276f",
    pageSizeOptions = "Mostrar {rows}",        
    # Accessible labels for assistive technologies such as screen readers.
    # These are already set by default, but don't forget to update them when
    # changing visible text.
    pagePreviousLabel = "Página anterior",
    pageNextLabel = "Siguiente página"
  )


reactable(
  data       = top_level,
  compact    = TRUE, # for minimum row height
  filterable = TRUE, # for individual column filters
  striped    = FALSE, # banded rows
  resizable  = FALSE, # for resizable column widths
  theme = nytimes( header_font_color = "#444444"),
  defaultPageSize=12,
  pageSizeOptions = c(12, 20, 30, 40, 100),
  showPageSizeOptions=TRUE,
  language = reactable_es_1,
  defaultColDef = colDef(
    filterable=FALSE,
    defaultSortOrder = "desc",
    minWidth = 30, maxWidth=50),
  columnGroups = list(colGroup(name = var_lang(deaths), columns =
                                 er.numerical.columns)),
  columns = list (
    date = colDef(name=var_lang(year), maxWidth=55,
                  cell = function(value) strftime(value, "%Y"),
                    defaultSortOrder = "asc",
                    filterable=TRUE, sortNALast = TRUE,
                    style = list(background = "#ffffff")),
    year = colDef (show = FALSE),
    # year = colDef (name="Year", maxWidth=60,
    #                defaultSortOrder = "asc",
    #                filterable=TRUE, sortNALast = TRUE,
    #                style = list(background = "#ffffff")),
    event_title = colDef (name="Evento", maxWidth=250,
                          defaultSortOrder = "asc",
                          filterable=TRUE,
                          style = list(fontWeight = "bold")),
    n = deaths_column(maxValue = max_deaths, name=var_lang(n)),
    n_state_perp = deaths_column(maxValue = max_deaths, 
                                 name=var_lang(n_state_perp),
                                 chosen_palette = perp_pal),
    n_state_victim = deaths_column(maxValue = max(max_deaths/2, max_sv_deaths),  
                                   # sets the maximum intensity 
                                   name=var_lang(n_state_victim),
                                   chosen_palette = sv_pal),
    n_state_separate = deaths_column(maxValue = max(max_deaths/2, max_sep_deaths),  
                                     # sets the maximum intensity 
                                     name=var_lang(n_state_separate),
                                     chosen_palette = sep_pal),
    protest_domain = colDef (name=var_lang(protest_domain),
                             defaultSortOrder = "asc",
                             filterable=TRUE,
                             maxWidth=150),
    pres_admin = colDef (name=var_lang(pres_admin),
                         defaultSortOrder = "asc",
                         filterable=TRUE, maxWidth=300),
    event_title_en = colDef(show = FALSE) # hidden matching column
  ),
  details = function(index) { # index is the row number of current row.
    # sub-table of only those students for current row.
    sec_lvl = second_level[second_level$event_title == top_level$event_title_en[index], ] 
    reactable(data       = sec_lvl,
              theme = nytimes( header_font_color = "#777777"),
              compact    = TRUE, 
              filterable = FALSE,
              bordered   = TRUE, 
              striped    = TRUE, # banded rows
              resizable  = FALSE,
              language = reactable_es_2,
              defaultPageSize=12,
              pageSizeOptions = c(6, 12, 20, 30, 100),
              columns    = list (
                event_title = colDef(show = FALSE),
                date = colDef(cell = function(value) strftime(value, "%d %b %Y"),
                              format = colFormat(locales = date_locale),
                               defaultSortOrder = "asc",
                              name=var_lang(date)),
                dec_firstname = colDef (name=var_lang(dec_firstname)),
                dec_surnames = colDef (name=var_lang(dec_firstname)),
                age = colDef (name="Edad", maxWidth=45),
                dec_affiliation = colDef (name=var_lang(dec_affiliation)),
                intentionality = colDef (name=var_lang(intentionality)),
                state_responsibility = colDef(name=var_lang(state_responsibility),
                                              defaultSortOrder = "asc",
                                              style = function(value, index) {
                                                if(is.na(value)){
                                                  list(color = "black")
                                                # } else if (value == "Separate"){
                                                #   list(color = state_resp.colors[["Separate"]])
                                                # } else if (value == "Perpetrator"){
                                                #   list(color = state_resp.colors[["Perpetrator"]])
                                                # } else if (value == "Victim"){
                                                #   list(color = state_resp.colors[["Victim"]])
                                                }else if(value %in%
                                                         c("Separado", "Perpetrador",
                                                           "Víctima")){
                                                  list(color = state_resp.colors_es[[value]])
                                                }else {
                                                  list(color = "black")
                                                }
                                              }),
                perp_affiliation = colDef(name=var_lang(perp_affiliation),
                                          defaultSortOrder = "asc"
                                          )
              )
    )
  }
)
cat(paste(datafiles_footer(),sep=""))
```

```{r reset-locale, include=FALSE}
sink(nullfile()) # suppress output
Sys.setlocale("LC_TIME", prev)
sink()           # end suppress output
```

